### ISSUE TITLE
{KeyError} 'text_embedding' in text_embedding_config

### ISSUE THREAD

**Issue by yaorong1996** [ZephyrZhuQi/ssbaseline#1]
## ❓ Questions and Help
What's the meaning in m4c.py "# TODO: add into yml embedding configs"?
how to get the text embedding config

**Comment by ZephyrZhuQi** [comment]
Hi,
This annotation was written to remind myself to add configs for **text_embeddings** into the yml file, and I did later in [configs/vqa/m4c_textvqa/m4c.yml](https://github.com/ZephyrZhuQi/ssbaseline/blob/ssbaseline/configs/vqa/m4c_textvqa/m4c.yml) and [configs/vqa/m4c_textvqa/m4c_sbd.yml](https://github.com/ZephyrZhuQi/ssbaseline/blob/ssbaseline/configs/vqa/m4c_textvqa/m4c_sbd.yml). The configs for text_embeddings specify the type and parameters, which are used to initialize the module **TextEmbedding**. 

For example, when the type is set as "attention_two", we get **AttentionTwoTextEmbedding** in [pythia/modules/embeddings.py](https://github.com/ZephyrZhuQi/ssbaseline/blob/ssbaseline/pythia/modules/embeddings.py). This module is to get question self-attention outputs, described in our paper Eq.(6)(7)(8).
