### ISSUE TITLE
ERROR: Key image_feature_2 not found in the SampleList

### ISSUE THREAD

**Issue by GoelPratyush** [ZephyrZhuQi/ssbaseline#3]
## ❓ Questions and Help
I am trying to generate the EvalAI prediction files for the TextVQA test set using SSBaseline model, but I am facing the following error:-

**Code to run the predictions**
`python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c --config configs/vqa/m4c_textvqa/m4c_with_stvqa.yml --save_dir save/m4c --run_type inference --evalai_inference 1 --resume_file data/models/best_textvqa_withStvqa.ckpt`

**Error**

> 2021-03-30T13:13:19 ERROR: Key image_feature_2 not found in the SampleList. Valid choices are ['question_id', 'image_id', 'image_feature_0', 'image_info_0', 'image_feature_1', 'image_info_1', 'text', 'text_len', 'obj_bbox_coordinates', 'context', 'context_tokens', 'context_tokens_enc', 'context_feature_0', 'context_info_0', 'context_feature_1', 'context_info_1', 'order_vectors', 'ocr_bbox_coordinates', 'sampled_idx_seq', 'train_prev_inds', 'dataset_type', 'dataset_name', 'dataset_type_', 'dataset_name_']
> Traceback (most recent call last):
>   File "tools/run.py", line 86, in <module>
>     run()
>   File "tools/run.py", line 75, in run
>     trainer.train()
>   File "/home/pratyush/ssbaseline/pythia/trainers/base_trainer.py", line 198, in train
>     self.inference()
>   File "/home/pratyush/ssbaseline/pythia/trainers/base_trainer.py", line 427, in inference
>     self._inference_run("test")
>   File "/home/pratyush/ssbaseline/pythia/trainers/base_trainer.py", line 431, in _inference_run
>     self.predict_for_evalai(dataset_type)
>   File "/home/pratyush/ssbaseline/pythia/trainers/base_trainer.py", line 472, in predict_for_evalai
>     model_output = self.model(prepared_batch)
>   File "/home/pratyush/ssbaseline/pythia/models/base_model.py", line 120, in __call__
>     model_output = super().__call__(sample_list, *args, **kwargs)
>   File "/home/pratyush/.virtualenvs/ssbase/lib/python3.8/site-packages/torch-1.4.0-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/pratyush/ssbaseline/pythia/models/m4c.py", line 209, in forward
>     self._forward_ocr_encoding(sample_list, fwd_results)
>   File "/home/pratyush/ssbaseline/pythia/models/m4c.py", line 263, in _forward_ocr_encoding
>     ocr_recogcnn = sample_list.image_feature_2[:, :ocr_fasttext.size(1), :]
>   File "/home/pratyush/ssbaseline/pythia/common/sample.py", line 145, in __getattr__
>     raise AttributeError(
> AttributeError: Key image_feature_2 not found in the SampleList. Valid choices are ['question_id', 'image_id', 'image_feature_0', 'image_info_0', 'image_feature_1', 'image_info_1', 'text', 'text_len', 'obj_bbox_coordinates', 'context', 'context_tokens', 'context_tokens_enc', 'context_feature_0', 'context_info_0', 'context_feature_1', 'context_info_1', 'order_vectors', 'ocr_bbox_coordinates', 'sampled_idx_seq', 'train_prev_inds', 'dataset_type', 'dataset_name', 'dataset_type_', 'dataset_name_']

Kindly, help me with this error or point me in the correct direction to resolve this issue. 

Thanks in advance.

**Comment by GoelPratyush** [comment]
Oh, I got it. I haven't added the address for the sbd_trans_transformer_feature in m4c_with_stvqa.yml. 😇

**Comment by zc1326387279** [comment]
Hi, thanks for the code you provided, when I was training on the STVQA dataset, the following problem occurred: INFO: Starting training...

ERROR: Caught RuntimeError in DataLoader worker process 0.

Original Traceback (most recent call last):

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data / _utils/worker. Py", line 198, in _worker_loop

data = fetcher.fetch(index)

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data / _utils/fetch. Py", line 47, fetch in

return self.collate_fn(data)

File "CRN_tvqa_modify/pythia/common/batch_collator.py", line 10, in __call__

sample_list = SampleList(batch)

File "CRN_tvqa_modify/pythia/common/sample.py", line 114, in __init__

self[field][idx] = self._get_data_copy(sample[field])

RuntimeError:  The expanded size of the tensor (4) must match the existing size (50) at non-singleton dimension 1.  Target sizes:  [50, 4].  Tensor sizes: [50]



Traceback (most recent call last):

File "tools/run.py", line 89, in &lt; module&gt;

run()

File "tools/run.py", line 78, in run

trainer.train()

File "CRN_tvqa_modify/pythia/trainers/base_trainer.py", line 226, in train

for batch in self.train_loader:

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 435, in __next__

data = self._next_data()

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 1085, in _next_data

return self._process_data(data)

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 1111, in _process_data

data.reraise()

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch / _utils. Py", line 428, in reraise

raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.

Original Traceback (most recent call last):

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data / _utils/worker. Py", line 198, in _worker_loop

data = fetcher.fetch(index)

The File "anaconda3 / envs/CRN/lib/python3.7 / site - packages/torch/utils/data / _utils/fetch. Py", line 47, fetch in

return self.collate_fn(data)

File "CRN_tvqa_modify/pythia/common/batch_collator.py", line 10, in __call__

sample_list = SampleList(batch)

File "CRN_tvqa_modify/pythia/common/sample.py", line 114, in __init__

self[field][idx] = self._get_data_copy(sample[field])

RuntimeError:  The expanded size of the tensor (4) must match the existing size (50) at non-singleton dimension 1.  Target sizes:  [50, 4].  Tensor sizes: [50]

How can I solve it?
