### ISSUE TITLE
请问可以提供sbdnet的训练模型吗？

### ISSUE THREAD

**Issue by daaidouya** [ZephyrZhuQi/ssbaseline#4]
## ❓ Questions and Help
请问可以提供sbdnet的训练模型吗？如果可以的话万分感谢！

**Comment by ZephyrZhuQi** [comment]
获得ocr检测框的代码：https://github.com/Yuliang-Liu/Box_Discretization_Network ，使用的模型是MLT 2017，可以在这个git repo中下载

**Comment by daaidouya** [comment]
看到了，谢谢！
