### ISSUE TITLE
textcaps部分有数据集和priject部分吗？

### ISSUE THREAD

**Issue by LYY19971206** [ZephyrZhuQi/ssbaseline#5]

**Comment by LYY19971206** [comment]
textcaps部分有数据集和project部分吗？

**Comment by leonodelee** [comment]
> textcaps部分有数据集和project部分吗？

请问您找到了吗？

**Comment by ZephyrZhuQi** [comment]
数据集(图片应该跟textvqa是一样的)：https://textvqa.org/textcaps/dataset/
评测网站：https://eval.ai/web/challenges/challenge-page/906/overview

**Comment by leonodelee** [comment]
> 数据集(图片应该跟textvqa是一样的)：https://textvqa.org/textcaps/dataset/ 评测网站：https://eval.ai/web/challenges/challenge-page/906/overview

请问textcap部分的annotation文件imdb/agem_textcaps能提供下吗

**Comment by LYY19971206** [comment]
抱歉，现在才看到这个邮件，可以＋vx联系吗？
我的vx： L18861850981





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZephyrZhuQi/ssbaseline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午4:25
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ZephyrZhuQi/ssbaseline] textcaps部分有数据集和priject部分吗？ (#5)





  
textcaps部分有数据集和project部分吗？
  
请问您找到了吗？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
