### ISSUE TITLE
Can not train ssbaseline-textcaps

### ISSUE THREAD

**Issue by leonodelee** [ZephyrZhuQi/ssbaseline#7]
## ❓ Questions and Help
Sorry to interrupt, I try to train your branch ssbaseline-textcaps but failed, could you please check it again?

**Comment by ZephyrZhuQi** [comment]
I added one commit to the existing m4c-textcaps. First make sure that you can train m4c-textcaps, then you can see by adding this commit, what might be the reason that it's not working.
